package:
  name: blockchain
  version: "0.0.1"

requirements:
  build:
    - python
    - setuptools

  run:
    - python =>3.6

about:
  home: https://github.com/tomcusack1/blockchain
  license: GPL-2.0
  summary: 'A Python implementation of a Blockchain'
